config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :gardens, only: [:index, :create, :new, :show] do
   resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index] do
    resources :reviews, only: [:new, :create, :index]
    member do
      patch "/accept", to: "bookings#accept"
      patch "/reject", to: "bookings#reject"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :garden
  has_many :reviews
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :description, presence: true
  validates :location, uniqueness: true, presence: true
  validates :price, presence: true
  validates :capacity, presence: true

  belongs_to :user
  has_many_attached :photos
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_many :bookings
  has_many :reviews, through: :bookings
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gardens, dependent: :destroy
  has_many :bookings
  has_many :host_bookings, through: :gardens, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = current_user.host_bookings.order(created_at: :asc)
    @booking_requests = current_user.bookings
  end

  def create
    @user = current_user #grabing the current user (helper method given be devise gem)
    @booking = Booking.new(booking_params) # creating a booking instance passing the strong params of the booking
    @garden = Garden.find(params[:garden_id]) #find the gardin id in the url
    @booking.garden = @garden #assigning the garden from the url as the garden of the booking we are creating
    @booking.user = @user # assigning the current user as a user of the booking we are creating

    if @booking.save
      flash[:alert] = " Booking requested!"
      redirect_to bookings_path
    else
      render :new
    end

  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to bookings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.status = "rejected"
    @booking.save
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :start_time, :end_time, :status)
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
     skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    @gardens = Garden.all
    if params[:q].present?
      @gardens = @gardens.near(params[:q], 20)
    end

    if params[:pool].present?
      @gardens = @gardens.where(pool: true)
    end

    if params[:barbecue].present?
      @gardens = @gardens.where(barbecue: true)
    end

    if params[:green_area].present?
      @gardens = @gardens.where(green_area: true)
    end

    if params[:capacity].present?
      @gardens = @gardens.where("capacity >= ?", params[:capacity])
    end

    @markers = @gardens.map do |garden|
      {
        lat: garden.latitude,
        lng: garden.longitude
      }
    end
  end

  def show
    @garden = Garden.find(params[:id])
    @review = Review.new
    @booking = Booking.new

    @markers = [{
      lat: @garden.latitude,
      lng: @garden.longitude
    }]

    @reviews = @garden.reviews
  end

  def new
    @garden = Garden.new
  end

  def create
    @user = current_user
    @garden = Garden.new(garden_params)
    @garden.user = @user
    if @garden.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  private

  def garden_params
    params.require(:garden).permit(:title, :description, :location, :price, :capacity, :barbecue,
   :pool, :green_area, photos:[])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
     skip_before_action :authenticate_user!, only: :home
  def home
  end

  def test_bookings
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    @review.save
    if @review.save
      flash[:alert] = "Review posted, thank you!"
      redirect_to bookings_path
    else
      render 'gardens/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="row border-bottom">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <div class="light-box-around">
      <p>Bookings (<%= @bookings.count %>)</p>
    </div>
  </div>
</div>
</div>

<div class="container-booking-requests">
  <div class="row mt-3">
  </div>
  <% @bookings.each do |booking| %>
  <div class="booking-card py-4 border-bottom">
    <div class="booking-picture">
      <%= image_tag "ellyn.png", class: "avatar"%>
    </div>

    <div class="booking-title">
      <p class="bold"> <%= booking.user.first_name %> <%= booking.user.last_name&.first %>.</p>
      <p class="lighter middle-gray"> <%= booking.created_at.strftime("%A, %b %d") %></p>
    </div>

    <div class="booking-price-location">
      <p class="bold">Total Income: <%= (booking.end_time - booking.start_time) * booking.garden.price %>€</p>
      <p class="lighter middle-gray"> <span class="location-text"> <%= booking.garden.location %> </span></p>
    </div>

    <div class="booking-dates">
     <p><span class="d-inline-block lighter middle-gray"><%= booking.date.strftime("%A, %b %d") %></span></p>
     <p><span class="d-inline-block lighter middle-gray"><%= booking.start_time %>:00 - <%= booking.end_time %>:00</span></p>
   </div>

 <!--   buttons depending on status of booking -->

   <% if booking.status == "pending"%>

    <div class="d-flex mt-2 justify-content-around">
      <div class="mr-1">
        <%= link_to "Accept", accept_booking_path(booking), method: :patch, class: "button background-green"%>
      </div>

      <div class="ml-1">
        <%= link_to "Reject", reject_booking_path(booking), method: :patch, class: "button background-orange"%>
      </div>
    </div>

  <% elsif booking.status == "accepted"%>
    <p class="fat-green-no-effect"> Booking confirmed! </p>

  <% else %>
    <p class="fat-orange"> Booking rejected! </p>

  <% end %>

</div>

<% end %>

</div>

<div class="row border-bottom">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <div class="light-box-around">
      <p>Requests (<%= @booking_requests.count %>)</p>
    </div>
  </div>
</div>
</div>

<div class="container-booking-requests">
  <div class="row mt-3">
  </div>
  <% @booking_requests.each do |booking| %>
  <div class="booking-card py-4 border-bottom">
    <div class="booking-picture">
      <%= cl_image_tag booking.garden.photos.first.key, class: "avatar"%>
    </div>

    <div class="booking-title">
      <p class="bold"> <%= booking.garden.title.truncate(12)%></p>
      <p class="lighter middle-gray"> <%= booking.created_at.strftime("%A, %b %d") %></p>
    </div>

    <div class="booking-price-location">
      <p class="bold">Price: <%=(booking.end_time - booking.start_time) * booking.garden.price %>€</p>
      <p class="lighter middle-gray"> <span class="location-text"> <%= booking.garden.location %> </span></p>
    </div>

    <div class="booking-dates">
     <p><span class="d-inline-block lighter middle-gray"><%= booking.date.strftime("%A, %b %d") %></span></p>
     <p><span class="d-inline-block lighter middle-gray"><%= booking.start_time %>:00 - <%= booking.end_time %>:00</span></p>
   </div>

 <!--   buttons depending on status of booking -->

   <% if booking.status == "accepted"%>

  <div>
   <p class="fat-green-no-effect"> Booking is confirmed! </p>
   <%= link_to "Create a Review", new_booking_review_path(booking), class: "button background-green" %>
  </div>

  <% elsif booking.status == "rejected"%>
    <p class="fat-orange"> Booking is rejected! </p>

  <% else %>
    <p class=> Booking is pending! </p>

  <% end %>

</div>

<% end %>

app/views/gardens/edit.html.erb
<h1>Gardens#edit</h1>
<p>Find me in app/views/gardens/edit.html.erb</p>

app/views/gardens/index.html.erb
<div class = "container main-container">
  <div class = "card-container">
    <div class="row mx-4 my-3">
      <%= form_with url: '/gardens', method: :get, local: true do |f| %>
      <div class="form-row">
        <div class='col-md-5 form-group'>
          <%= f.text_field :q, id: :q, class: 'form-control index-search', placeholder: "Location" %>
        </div>
        <div class='col-md-4 form-group'>
          <%= f.text_field :capacity, class: 'form-control index-search', placeholder: "Nr. of people" %>
        </div>
        <div class='col-md-2 form-group'>
          <%= f.submit "Filter", class: 'btn btn-success btn-search-form' %>
        </div>
      </div>
      <div class= 'form-check form-check-inline'>
        <%= check_box_tag :pool, class: 'form-check-input search-checkbox' %>
        <%= label_tag :pool, ("Pool"), class: 'form-check-label search-checkbox' %>
      </div>
      <div class= 'form-check form-check-inline'>
        <%= check_box_tag :barbecue, class: 'form-check-input' %>
        <%= label_tag :barbecue, ("Barbecue"), class: 'form-check-label search-checkbox' %>
      </div>
      <div class= 'form-check form-check-inline'>
        <%= check_box_tag :green_area, class: 'form-check-input' %>
        <%= label_tag :green_area, ("Green area"), class: 'form-check-label search-checkbox' %>
      </div>
      <% end %>
    </div>

    <h2 class="ml-3">We found <span class="fat-green"> <%= @gardens.count(:all) %> </span> gardens</h2>
  <% @gardens.each do |garden| %>
    <div class = "row mx-3 py-4 border-top">
      <div class = "garden-card">
        <div class="garden-img">
        <%= link_to garden_path(garden) do %>
          <% if garden.photos.attached? %>
            <%= cl_image_tag garden.photos.first.key, height: 200, width: 300, crop: :fill %>
          <% else %>
            <%= image_tag "Garden2.jpg", height: 200, width: 300, crop: :fill %>
          <% end %>
        <% end %>
        </div>
        <div class="garden-info p-2">
          <div class="garden-title">
            <p> <%= link_to garden.title, garden_path(garden), class: "fat-green"%></p>
          </div>
          <div class="garden-amenities">
            <ul class="list-inline">
            <% if garden.barbecue == true %>
              <li class="list-inline-item"> <i class="fas fa-hamburger"></i> Grill </li>
            <% end %>
            <% if garden.green_area == true %>
              <li class="list-inline-item"> <i class="fas fa-seedling"></i> Green Area </li>
            <% end %>
            <% if garden.pool == true %>
              <li class="list-inline-item"> <i class="fas fa-swimming-pool"></i> Pool </li>
            <% end %>
            </ul>
          </div>

            <div class="garden-description">
              <p> <%= garden.description %></p>
            </div>
            <div class="d-flex justify-content-between align-items-center">
            <div class="garden-price">
              <h2> <%= garden.price %> $ <span class="smaller-text">/ hour </span> </h2>
            </div>
            <div class="garden-link">
              <p><i class="fas fa-star"></i> 5</p>
            </div>
            </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>


  <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    <% @markers.each do |marker| %>
    <% end %>
  </div>

</div>

app/views/gardens/new.html.erb
<div class="container-form">
  <!-- Form -->
  <div class="form-grid">
    <div class="whitespace">
    </div>

    <div class="form">
      <h1 class="fat-green">Create your Garden</h1>
      <!-- app/views/restaurants/_form.html.erb -->
      <%= simple_form_for(@garden) do |f| %>
        <% if @garden.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @garden.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.input :title, placeholder: 'Title', label:false, class: 'form-control' %>
        <%= f.input :description, placeholder: 'Description', label:false,class: 'form-control' %>
        <%= f.input :location, placeholder: 'Location', label:false,class: 'form-control' %>
        <%= f.input :price, placeholder: 'Price', label:false,class: 'form-control'%>
        <%= f.input :capacity, placeholder: 'Capacity', label:false, class: 'form-control' %>
        <%= f.input :barbecue, class: 'form-control' %>
        <%= f.input :pool, class: 'form-control' %>
        <%= f.input :green_area, class: 'form-control' %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }, class: 'form-control' %>
        <%= f.submit "Create new Garden", class: "btn btn-success w-100"%>
      <% end %>
    </div>

    <div class="whitespace">
    </div>

  </div>

  <div>
    <%= image_tag "Garden_Vertical.jpg", class: "form-image"%>
  </div>
</div>

app/views/gardens/show.html.erb
<div class = "container show">

  <div class="d-flex justify-content-between mt-4">
    <div class="card-title">
      <h3><%=@garden.title%></h3>
    </div>
    <div>
      <%= link_to "Back to Gardens", gardens_path, class: "backlink"%>
    </div>
  </div>

  <div class="garden-photo">
    <% if @garden.photos.attached? %>
      <%= cl_image_tag @garden.photos.first.key, class: "show-image" %>
    <% else %>
      <%= image_tag "Garden2.jpg", class: "show-image" %>
    <% end %>
  </div>

  <div class="garden-container">
    <div class="garden-info-container">
        <h4><%=@garden.description%></h4>
        <ul class="list-inline show-icons border-bottom">
          <li class="list-inline-item"> <i class="fas fa-user-friends"></i> <%=@garden.capacity%> people</li>
          <% if @garden.barbecue == true %>
            <li class="list-inline-item"> <i class="fas fa-hamburger"></i> Grill </li>
          <% end %>
          <% if @garden.green_area == true %>
            <li class="list-inline-item"> <i class="fas fa-seedling"></i> Green Area </li>
          <% end %>
          <% if @garden.pool == true %>
            <li class="list-inline-item"> <i class="fas fa-swimming-pool"></i> Pool </li>
          <% end %>
        </ul>

        <div class= "margin-bottom-big border-bottom"> Top garden with everything you need for your family or friends. We take care that everything is clean and ready when you come and ask you to do the same when you leave. Enjoy an amazing stay and leave us a good review if you liked it, so more people can come to our lovely home. </div>

        <div class="review-container">
          <h2><b>Reviews</b></h2>
          <div class="rating p-3 border-bottom">
            <i class="fas fa-star"></i> 5
          </div>
          <div class="container reviews-container py-2">

          <% @reviews.each do |review| %>

            <div class="row review border-bottom">
              <div class="review-card">
                  <div class="container-avatar+name d-flex py-2 align-items-center">
                  <div><%= image_tag "ellyn.png", class: "avatar"%></div>
                  <div class="name px-4"> <%= review.booking.user.first_name %> </div>
                </div>
                <div class="review description py-1">
                  <p> <%= review.content  %> </p>
                </div>
              </div>
            </div>

          <% end %>


          </div>
        </div>

        <div class="garden-location">
          <div class="location py-2">
            <%=@garden.location%>
          </div>
          <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>

    </div>

    <div class="garden-booking border">
      <h2><b><%=@garden.price%>$/hour</b></h2>

      <div class="form">
        <%= simple_form_for [@garden, @booking] do |f| %>
        <%= f.input :date, placeholder: 'Date', label: false, as: :string, input_html: {class: "datepicker"} %>
        <div class="d-flex justify-content-between">
          <%= f.input :start_time, prompt: 'Start time', label: false,collection: (0..24).to_a, input_html: {style: 'width: 150px'} %>
          <%= f.input :end_time, prompt: 'End time', label: false,collection: (0..24).to_a, input_html: {style: 'width: 150px'} %>
        </div>
        <div class="d-flex justify-content-between">
          <p>Total</p>
          <div class="calculation" data-price="<%= @garden.price %>">
            _
          </div>
        </div>
        <%= f.submit "Book", class: "btn btn-success w-100"%>
        <% end %>
      </div>
    </div>

  </div>

<!--  @garden.reviews.each do |review|
  review.content
  review.booking.user.name -->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan+2&display=swap" rel="stylesheet">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path 'Garden.jpg'%>')">
  <div class='container'>
    <h1>Book<strong> gardens</strong> <strong>online</strong></h1>
    <p>Spend an amazing time with your friends in beautiful gardens around you.</p>
    <br>
    <p class="no-spacing lighter"><strong>Where do you want to chill?</strong></p>
      <%= form_with url: '/gardens', method: :get, local: true do |f| %>
      <%= f.text_field :q, id: :q, class: "form-home", placeholder: "Sidney" %>
      <%= f.submit "Book a Garden", class: 'btn btn-success btn-search-form' %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container-form">
  <!-- Form -->
  <div class="form-grid">
    <div class="whitespace">
    </div>

    <div class="form">
      <h1 class="fat-green">Leave a Review</h1>
      <!-- app/views/restaurants/_form.html.erb -->
      <h2>Tell us how you liked the Garden</h2>
        <%= simple_form_for [@booking, @review] do |f| %>
         <%= f.input :content, label: false, class: 'form-control', :input_html => {style: 'width: 700px'}  %>
         <%= f.submit "Post", class: "btn btn-light" %>
        <% end %>

    </div>

    <div class="whitespace">
    </div>

  </div>

  <div>
    <%= image_tag "Garden_Vertical.jpg", class: "form-image"%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="col-md-4">
  <div class="footer-links justify-content-center">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>

  <div class="col-md-4 text-center">
     <p>© Get Your Garden Inc.</p>
  </div>

  <div class="col-md-4 text-left ml-5">
    <div class="footer-copyright">
    <p>About us</p>
    <p>Company Details</p>
    <p>info@get-your-garden.com</p>
  </div>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
<%= image_tag "garden-logo-vector.jpg", alt: "Get-Your-Garden" %>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item <%= 'active' if current_page?(controller: '/pages', action: 'home') %>" >
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(controller: '/gardens', action: 'index') %>">
        <a class="nav-link" href="/gardens">Find gardens</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(controller: '/gardens', action: 'new') %>">
        <%= link_to "Create a Garden", new_garden_path, class: "nav-link"%>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Bookings", bookings_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>